// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mbfyakzidmodsluqwuux.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1iZnlha3ppZG1vZHNsdXF3dXV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5NDE5NzEsImV4cCI6MjA2ODUxNzk3MX0.DVi-HCojhVrljyzUHn-R6zzc14bbsHfvCGGKZcCYfZw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});